[[plugins]]
== Plugins
Dueuno leverages the Apache Grails plugins infrastructure adding some useful methods.

=== onPluginInstall()
Gets executed only the first time the application is run or when a new Dueuno Plugin is added as a dependency in `build.gradle`. It is used to install the plugin.

.grails-app/init/BootStrap.groovy
[source,groovy]
----
class BootStrap {

    ApplicationService applicationService

    def init = {

        applicationService.onPluginInstall { String tenantId ->
            // ...
        }

    }
}
----

=== beforeInit()
Available in Dueuno plugins. It runs before the application is initialized. The session is not available, so session variables cannot be set here.

NOTE: This method is executed only when configured in a plugin, it does not get executed if implemented in the application.

.grails-app/init/BootStrap.groovy
[source,groovy]
----
class BootStrap {

    ApplicationService applicationService

    def init = {

        applicationService.beforeInit {
            // ...
        }

    }
}
----

=== afterInit()
Available in Dueuno plugins. It runs after the application is initialized. The session is not available, so session variables cannot be set here.

NOTE: This method is executed only when configured in a plugin, it does not get executed if implemented in the application.

.grails-app/init/BootStrap.groovy
[source,groovy]
----
class BootStrap {

    ApplicationService applicationService

    def init = {

        applicationService.afterInit {
            // ...
        }

    }
}
----
////
Licensed to the Apache Software Foundation (ASF) under one or more
contributor license agreements. See the NOTICE file distributed with
this work for additional information regarding copyright ownership.
The ASF licenses this file to you under the Apache License, Version 2.0.
You may obtain a copy of the License at

    https://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
////
